### ISSUE TITLE
[BUG] Login stops working after keycloak pod is restarted

### ISSUE THREAD

**Issue by ibragins** [konveyor/operator#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Critical

### Current Behavior

Login stops working, keycloak's pod contains multiple errors

### Expected Behavior

Pod should recover after restart and work as usual

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Deploy Tackle
2. Do first login, change password to non-default one
3. Make sure you can login with the new password
4. Restart pods
5. Try to login again
6. Check keycloak's pod for errors (oc logs ...)

### Environment

```markdown
- OS:
```

### Anything else?

```
15:13:35,340 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
15:13:35,362 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
```

```
15:14:01,639 ERROR [org.jboss.modcluster] (ServerService Thread Pool -- 56) MODCLUSTER000034: Failed to start advertise listener: java.net.SocketException: bad argument for IP_MULTICAST_IF: address not bound to any interface
        at java.base/java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
        at java.base/java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:91)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:371)
        at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:477)
        at org.jboss.mod_cluster.core@1.4.4.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.init(AdvertiseListenerImpl.java:151)
        at org.jboss.mod_cluster.core@1.4.4.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.start(AdvertiseListenerImpl.java:161)
        at org.jboss.mod_cluster.core@1.4.4.Final//org.jboss.modcluster.ModClusterService.init(ModClusterService.java:166)
        at org.wildfly.mod_cluster.undertow@26.1.1.Final//org.wildfly.mod_cluster.undertow.UndertowEventHandlerAdapterService.start(UndertowEventHandlerAdapterService.java:83)
        at org.wildfly.clustering.service@26.1.1.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

```
18:30:05,558 WARN  [org.keycloak.events] (default task-7) type=LOGIN_ERROR, realmId=a44fa203-7a2d-4641-b43a-210a8bd2c8ee, clientId=tackle-ui, userId=430a3636-3d69-4103-bb83-e88e1a98bb64, ipAddress=::ffff:10.128.2.2, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://tackle-konveyor-tackle.apps.mig01.rhos-psi.cnv-qe.rhood.us/, code_id=b8603429-f9a5-4e02-91ab-4c253b62e4ed, username=admin, authSessionParentId=b8603429-f9a5-4e02-91ab-4c253b62e4ed, authSessionTabId=TiSW2LJJFdk
19:19:48,307 WARN  [org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory] (ConnectionValidator) IJ030027: Destroying connection that is not valid, due to the following exception: org.postgresql.jdbc.PgConnection@2bc8d924: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.jdbc@42.3.3//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
        at org.postgresql.jdbc@42.3.3//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.CheckValidConnectionSQL.isValidConnection(CheckValidConnectionSQL.java:74)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnectionFactory.isValidConnection(BaseWrapperManagedConnectionFactory.java:1372)
        at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnectionFactory.getInvalidConnections(BaseWrapperManagedConnectionFactory.java:1179)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.validateConnections(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1450)
        at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.pool.validator.ConnectionValidator$ConnectionValidatorRunner.run(ConnectionValidator.java:285)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException
        at org.postgresql.jdbc@42.3.3//org.postgresql.core.PGStream.receiveChar(PGStream.java:455)
        at org.postgresql.jdbc@42.3.3//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2119)
        at org.postgresql.jdbc@42.3.3//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
        ... 14 more
```

**Comment by dymurray** [comment]
Doesn't seem to be an issue any longer, closing
